# Generated by Django 4.0 on 2022-01-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0002_rename__id_tablemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedmodel',
            name='booked_date',
            field=models.DateTimeField(primary_key=True, serialize=False, unique=True),
        ),
    ]
