# Generated by Django 4.0 on 2022-01-06 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0003_alter_bookedmodel_booked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='booked_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='bookedmodel',
            unique_together={('booked_date', 'table_id')},
        ),
    ]
