# Generated by Django 4.0 on 2022-01-12 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0004_bookedmodel_id_alter_bookedmodel_booked_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='booked_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
