# Generated by Django 4.0 on 2022-01-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0005_remove_bookedmodel_id_alter_bookedmodel_booked_uid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedmodel',
            unique_together=set(),
        ),
    ]
